const StateCodes = [
  {key: "AC", value: "AC"},
  {key: "AL", value: "AL"},
  {key: "AM", value: "AM"},
  {key: "AP", value: "AP"},
  {key: "BA", value: "BA"},
  {key: "CE", value: "CE"},
  {key: "DF", value: "DF"},
  {key: "ES", value: "ES"},
  {key: "GO", value: "GO"},
  {key: "MA", value: "MA"},
  {key: "MG", value: "MG"},
  {key: "MS", value: "MS"},
  {key: "MT", value: "MT"},
  {key: "PA", value: "PA"},
  {key: "PB", value: "PB"},
  {key: "PE", value: "PE"},
  {key: "PI", value: "PI"},
  {key: "PR", value: "PR"},
  {key: "RJ", value: "RJ"},
  {key: "RN", value: "RN"},
  {key: "RO", value: "RO"},
  {key: "RR", value: "RR"},
  {key: "RS", value: "RS"},
  {key: "SC", value: "SC"},
  {key: "SE", value: "SE"},
  {key: "SP", value: "SP"},
  {key: "TO", value: "TO"}
];

export default StateCodes;
